[nixpkgs]
src.git = "https://github.com/nixos/nixpkgs"
fetch.git = "https://github.com/nixos/nixpkgs"
git.branch = "nixpkgs-21.05"

[nixpkgs-unstable]
src.git = "https://github.com/nixos/nixpkgs"
fetch.git = "https://github.com/nixos/nixpkgs"
git.branch = "nixpkgs-unstable"

[holochain_develop]
src.git = "https://github.com/holochain/holochain"
fetch.git = "https://github.com/holochain/holochain"
src.git_branch = "develop"
cargo_lock = "Cargo.lock"

[holochain_main]
src.git = "https://github.com/holochain/holochain"
fetch.git = "https://github.com/holochain/holochain"
src.git_branch = "main"
cargo_lock = "Cargo.lock"
