# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl }:
{
  holochain_develop = {
    pname = "holochain_develop";
    version = "05c939784ac8aed6a8e2db416f8bed0b73980c32";
    src = fetchgit {
      url = "https://github.com/holochain/holochain";
      rev = "05c939784ac8aed6a8e2db416f8bed0b73980c32";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "11g1b6219ikcirk0zva1c1laiav4xhl7cwy10jq6nxgpb77gb7zn";
    };
    cargoLock = {
      lockFile = ./holochain_develop-05c939784ac8aed6a8e2db416f8bed0b73980c32/Cargo.lock;
      outputHashes = {
        "cargo-test-macro-0.1.0" = "1yy1y1d523xdzwg1gc77pigbcwsbawmy4b7vw8v21m7q957sk0c4";
      };
    };
  };
  holochain_main = {
    pname = "holochain_main";
    version = "05c939784ac8aed6a8e2db416f8bed0b73980c32";
    src = fetchgit {
      url = "https://github.com/holochain/holochain";
      rev = "05c939784ac8aed6a8e2db416f8bed0b73980c32";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "11g1b6219ikcirk0zva1c1laiav4xhl7cwy10jq6nxgpb77gb7zn";
    };
    cargoLock = {
      lockFile = ./holochain_main-05c939784ac8aed6a8e2db416f8bed0b73980c32/Cargo.lock;
      outputHashes = {
        "cargo-test-macro-0.1.0" = "1yy1y1d523xdzwg1gc77pigbcwsbawmy4b7vw8v21m7q957sk0c4";
      };
    };
  };
  lair_develop = {
    pname = "lair_develop";
    version = "bd92b76ad9cc18bc0c0db215e4bea9767c9003cf";
    src = fetchgit {
      url = "https://github.com/holochain/lair";
      rev = "bd92b76ad9cc18bc0c0db215e4bea9767c9003cf";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "12n1h94b1r410lbdg4waj5jsx3rafscnw5qnhz3ky98lkdc1mnl3";
    };
    cargoLock = {
      lockFile = ./lair_develop-bd92b76ad9cc18bc0c0db215e4bea9767c9003cf/Cargo.lock;
      outputHashes = {
        
      };
    };
  };
  lair_main = {
    pname = "lair_main";
    version = "bd92b76ad9cc18bc0c0db215e4bea9767c9003cf";
    src = fetchgit {
      url = "https://github.com/holochain/lair";
      rev = "bd92b76ad9cc18bc0c0db215e4bea9767c9003cf";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "12n1h94b1r410lbdg4waj5jsx3rafscnw5qnhz3ky98lkdc1mnl3";
    };
    cargoLock = {
      lockFile = ./lair_main-bd92b76ad9cc18bc0c0db215e4bea9767c9003cf/Cargo.lock;
      outputHashes = {
        
      };
    };
  };
  nixpkgs = {
    pname = "nixpkgs";
    version = "9899f2b5602a6a8be6e79725d39856025861a5d0";
    src = fetchgit {
      url = "https://github.com/nixos/nixpkgs";
      rev = "9899f2b5602a6a8be6e79725d39856025861a5d0";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "0zb05xxhy1zynpf9014a3jrv6hibs0zz855vc8x4x5hcjpx34dlc";
    };
  };
  nixpkgs-unstable = {
    pname = "nixpkgs-unstable";
    version = "9899f2b5602a6a8be6e79725d39856025861a5d0";
    src = fetchgit {
      url = "https://github.com/nixos/nixpkgs";
      rev = "9899f2b5602a6a8be6e79725d39856025861a5d0";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "0zb05xxhy1zynpf9014a3jrv6hibs0zz855vc8x4x5hcjpx34dlc";
    };
  };
  rust-overlay = {
    pname = "rust-overlay";
    version = "9c2fc6a62ccbc6f420d71ecac6bf0b84dbbee64f";
    src = fetchgit {
      url = "https://github.com/oxalica/rust-overlay";
      rev = "9c2fc6a62ccbc6f420d71ecac6bf0b84dbbee64f";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "0sm8kpainjladjfg4x8vnh2ra4sicsnpa7yv4gam3gbn6vp1ax4h";
    };
  };
}
